basePath: /api/v1
definitions:
  user_owner_internal_dto.CreateOrderRequest:
    properties:
      city:
        type: string
      price:
        minimum: 0
        type: number
      region:
        type: string
    required:
    - city
    - price
    - region
    type: object
  user_owner_internal_dto.CreateUserReq:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      logo:
        type: string
      name:
        type: string
      password:
        type: string
      phone_number:
        type: string
      updated_at:
        type: string
    required:
    - email
    - name
    - password
    - phone_number
    type: object
  user_owner_internal_dto.LoginReq:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
host: localhost:8080
info:
  contact: {}
  description: Test Swagger
  title: Test API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Authenticate user and return token
      parameters:
      - description: Login request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user_owner_internal_dto.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: User login
      tags:
      - auth
  /protected/orders:
    post:
      consumes:
      - application/json
      description: Create a new order with user information and location details
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Order creation request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user_owner_internal_dto.CreateOrderRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Order created successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Create a new order
      tags:
      - orders
  /users:
    get:
      consumes:
      - application/json
      description: Retrieve all users from the database
      produces:
      - application/json
      responses:
        "200":
          description: List of users
          schema:
            items:
              additionalProperties: true
              type: object
            type: array
        "500":
          description: Failed to get users
          schema:
            additionalProperties: true
            type: object
      summary: Get all users
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Create a new user with name, password, phone number, email and
        logo
      parameters:
      - description: User creation request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user_owner_internal_dto.CreateUserReq'
      produces:
      - application/json
      responses:
        "201":
          description: User created successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid request body or missing required fields
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Failed to create user
          schema:
            additionalProperties: true
            type: object
      summary: Create a new user
      tags:
      - users
swagger: "2.0"
